apiVersion: apps/v1
kind: Deployment
metadata:
  name: pritam-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: nginx
        ports:
        - containerPort: 80
