apiVersion: v1
kind: Namespace
metadata:
  name: ingress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: ingress
spec:
  selector: 
    matchLabels: 
      app: demo-app
  replicas: 1
  template: #Template for PODs
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: pritamrgb/service-for-ingress
        resources:
          requests:
            memory: 512Mi
            cpu: 0.5
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: ingress
spec:
  selector:
    app: demo-app
  ports:
    - name: http
      port: 80
  type: ClusterIP
            
            
            
